# Generated by Django 4.0.2 on 2022-02-17 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_sport_team_delete_sports_delete_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.team'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
