# Generated by Django 4.0.2 on 2022-02-17 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_planningtype_usertype_alter_garminsport_sport_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.usertype'),
        ),
    ]
