# Generated by Django 4.0.2 on 2022-02-17 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.usertype'),
        ),
    ]
