# Generated by Django 4.0.2 on 2022-02-27 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0019_athletecoach_plan_garminactivity_garmin_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garmin_id', models.CharField(blank=True, max_length=200)),
                ('garmincookies', models.TextField(blank=True)),
                ('garmin_user', models.CharField(blank=True, max_length=200)),
                ('garmin_password', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='garmin_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='garmin_password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='garmin_user',
        ),
        migrations.DeleteModel(
            name='CacheData',
        ),
    ]
