# Generated by Django 4.0.2 on 2022-02-27 02:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0020_garminprofile_remove_profile_garmin_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GarminActivity',
            new_name='GarminActivities',
        ),
    ]
