# Generated by Django 4.0.2 on 2022-02-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_garminprofile_garmin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garminprofile',
            name='garmin_user_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
