# Generated by Django 4.0.2 on 2022-03-04 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_garminprofile_garmin_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garminactivities',
            name='garmin_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planactivities',
            name='activity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='planificado', to='dashboard.activity'),
        ),
        migrations.AlterField(
            model_name='planactivities',
            name='plan',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='dashboard.plan'),
        ),
    ]
